version: "3.8"

services:
  # Override auth-api for development with hot reload
  auth-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: auth_api_dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/tmp # Exclude air tmp directory
      - go_modules:/go/pkg/mod # Cache Go modules
    working_dir: /app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - default
      - shared-api-network

volumes:
  go_modules:

networks:
  shared-api-network:
    external: true
