package main

import (
	"fmt"
	"log"

	"github.com/gin-gonic/gin"
	"github.com/joho/godotenv"
	"github.com/spf13/viper"

	_ "github.com/gjovanovicst/auth_api/docs" // docs is generated by Swag CLI
	"github.com/gjovanovicst/auth_api/internal/admin"
	"github.com/gjovanovicst/auth_api/internal/database"
	"github.com/gjovanovicst/auth_api/internal/email"
	logService "github.com/gjovanovicst/auth_api/internal/log"
	"github.com/gjovanovicst/auth_api/internal/middleware"
	"github.com/gjovanovicst/auth_api/internal/redis"
	"github.com/gjovanovicst/auth_api/internal/social"
	"github.com/gjovanovicst/auth_api/internal/twofa"
	"github.com/gjovanovicst/auth_api/internal/user"
	"github.com/gjovanovicst/auth_api/web"
	"github.com/gjovanovicst/auth_api/web/static"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title           Authentication and Authorization API
// @version         1.1.0
// @description     This is a sample authentication and authorization API built with Go and Gin.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
// @description Type "Bearer" + your JWT token

// @securityDefinitions.apikey AppID
// @in header
// @name X-App-ID
// @description The UUID of the application context

// @securityDefinitions.apikey AdminApiKey
// @in header
// @name X-Admin-API-Key
// @description Admin API Key for protected admin routes

// @securityDefinitions.apikey AppApiKey
// @in header
// @name X-App-API-Key
// @description Per-application API Key for app-scoped routes

func main() {
	// Load environment variables from .env file
	if err := godotenv.Load(); err != nil {
		log.Println("No .env file found, relying on environment variables")
	}

	// Initialize Viper for configuration management
	viper.AutomaticEnv() // Read environment variables
	viper.SetDefault("PORT", "8080")
	viper.SetDefault("ACCESS_TOKEN_EXPIRATION_MINUTES", 15)
	viper.SetDefault("REFRESH_TOKEN_EXPIRATION_HOURS", 720)

	// Connect to database
	database.ConnectDatabase()

	// Connect to Redis
	redis.ConnectRedis()

	// Run database migrations
	database.MigrateDatabase()

	// Initialize Activity Log Service
	logService.InitializeLogService()

	// Initialize Activity Log Cleanup Service
	cleanupService := logService.InitializeCleanupService(database.DB)
	if cleanupService != nil {
		// Ensure graceful shutdown of cleanup service
		defer cleanupService.Shutdown()
	}

	// Initialize Services and Handlers
	userRepo := user.NewRepository(database.DB)
	socialRepo := social.NewRepository(database.DB)
	logRepo := logService.NewRepository(database.DB)
	emailRepo := email.NewRepository(database.DB)
	emailService := email.NewService(emailRepo, database.DB)
	userService := user.NewService(userRepo, emailService, database.DB)
	socialService := social.NewService(userRepo, socialRepo)
	twofaService := twofa.NewService(userRepo, database.DB, emailService)
	logQueryService := logService.NewQueryService(logRepo)
	userHandler := user.NewHandler(userService)
	socialHandler := social.NewHandler(socialService)
	twofaHandler := twofa.NewHandler(twofaService)
	logHandler := logService.NewHandler(logQueryService)
	adminRepo := admin.NewRepository(database.DB)
	adminHandler := admin.NewHandler(adminRepo, emailService)

	// Initialize Admin GUI Services and Handler
	accountRepo := admin.NewAccountRepository(database.DB)
	accountService := admin.NewAccountService(accountRepo)
	dashboardService := admin.NewDashboardService(database.DB)
	settingsRepo := admin.NewSettingsRepository(database.DB)
	settingsService := admin.NewSettingsService(settingsRepo)
	guiHandler := admin.NewGUIHandler(accountService, dashboardService, adminRepo, settingsService, emailService)

	// Setup Gin Router
	r := gin.Default()

	// Initialize template renderer for GUI
	renderer, err := web.NewRenderer()
	if err != nil {
		log.Fatalf("Failed to initialize template renderer: %v", err)
	}
	r.HTMLRender = renderer

	// Add security headers middleware (before CORS so headers are always set)
	r.Use(middleware.SecurityHeadersMiddleware())

	// Add CORS middleware
	r.Use(middleware.CORSMiddleware())
	r.Use(middleware.AppIDMiddleware())

	// Public routes (with rate limiting)
	public := r.Group("/")
	{
		public.POST("/register", middleware.APIRegisterRateLimit(), userHandler.Register)
		public.POST("/login", middleware.APILoginRateLimit(), userHandler.Login)
		public.POST("/refresh-token", middleware.APIRefreshTokenRateLimit(), userHandler.RefreshToken)
		public.POST("/forgot-password", middleware.APIForgotPasswordRateLimit(), userHandler.ForgotPassword)
		public.POST("/reset-password", middleware.APIResetPasswordRateLimit(), userHandler.ResetPassword)
		public.GET("/verify-email", userHandler.VerifyEmail)
		// 2FA login verification (public because it needs temp token)
		public.POST("/2fa/login-verify", middleware.API2FAVerifyRateLimit(), twofaHandler.VerifyLogin)
		// 2FA email code resend (public because it needs temp token during login)
		public.POST("/2fa/email/resend", middleware.API2FAVerifyRateLimit(), twofaHandler.ResendEmail2FACode)
		// 2FA available methods (public so login UI can show method options)
		public.GET("/2fa/methods", twofaHandler.GetAvailableMethods)
	}

	// Social authentication routes
	auth := r.Group("/auth")
	{
		// Google OAuth2
		auth.GET("/google/login", socialHandler.GoogleLogin)
		auth.GET("/google/callback", socialHandler.GoogleCallback)

		// Facebook OAuth2
		auth.GET("/facebook/login", socialHandler.FacebookLogin)
		auth.GET("/facebook/callback", socialHandler.FacebookCallback)

		// GitHub OAuth2
		auth.GET("/github/login", socialHandler.GithubLogin)
		auth.GET("/github/callback", socialHandler.GithubCallback)
	}

	// Protected routes (require JWT authentication)
	protected := r.Group("/")
	protected.Use(middleware.AuthMiddleware())
	{
		// User profile routes
		protected.GET("/profile", userHandler.GetProfile)
		protected.PUT("/profile", userHandler.UpdateProfile)
		protected.DELETE("/profile", userHandler.DeleteAccount)
		protected.PUT("/profile/email", userHandler.UpdateEmail)
		protected.PUT("/profile/password", userHandler.UpdatePassword)

		// Auth routes
		protected.GET("/auth/validate", userHandler.ValidateToken)
		protected.POST("/logout", userHandler.Logout)

		// 2FA management routes
		protected.POST("/2fa/generate", twofaHandler.Generate2FA)
		protected.POST("/2fa/verify-setup", twofaHandler.VerifySetup)
		protected.POST("/2fa/enable", twofaHandler.Enable2FA)
		protected.POST("/2fa/disable", twofaHandler.Disable2FA)
		protected.POST("/2fa/recovery-codes", twofaHandler.GenerateRecoveryCodes)
		// Email 2FA routes
		protected.POST("/2fa/email/enable", twofaHandler.EnableEmail2FA)

		// Activity log routes
		protected.GET("/activity-logs", logHandler.GetUserActivityLogs)
		protected.GET("/activity-logs/event-types", logHandler.GetEventTypes)
		protected.GET("/activity-logs/:id", logHandler.GetActivityLogByID)
	}

	// Admin routes (protected by Admin API Key)
	adminRoutes := r.Group("/admin")
	// Remove the general AuthMiddleware and replace with AdminAuthMiddleware
	// Admin routes shouldn't require user tokens, but a specific admin key
	adminRoutes.Use(middleware.AdminAuthMiddleware(adminRepo))
	{
		adminRoutes.GET("/activity-logs", logHandler.GetAllActivityLogs)

		// Multi-tenancy Management
		adminRoutes.POST("/tenants", adminHandler.CreateTenant)
		adminRoutes.GET("/tenants", adminHandler.ListTenants)
		adminRoutes.POST("/apps", adminHandler.CreateApp)
		adminRoutes.GET("/apps/:id", adminHandler.GetAppDetails)
		adminRoutes.POST("/apps/:id/oauth-config", adminHandler.UpsertOAuthConfig)

		// Email management API
		adminRoutes.GET("/email-types", adminHandler.ListEmailTypes)
		adminRoutes.GET("/email-types/:code", adminHandler.GetEmailType)
		adminRoutes.GET("/email-variables", adminHandler.ListWellKnownVariables)
		adminRoutes.GET("/email-templates", adminHandler.ListEmailTemplates)
		adminRoutes.GET("/email-templates/:id", adminHandler.GetEmailTemplate)
		adminRoutes.POST("/email-templates", adminHandler.SaveEmailTemplate)
		adminRoutes.DELETE("/email-templates/:id", adminHandler.DeleteEmailTemplate)
		adminRoutes.POST("/email-templates/preview", adminHandler.PreviewEmailTemplate)
		adminRoutes.GET("/apps/:id/email-config", adminHandler.GetEmailServerConfig)
		adminRoutes.PUT("/apps/:id/email-config", adminHandler.SaveEmailServerConfig)
		adminRoutes.DELETE("/apps/:id/email-config", adminHandler.DeleteEmailServerConfig)
		adminRoutes.POST("/apps/:id/email-test", adminHandler.SendTestEmail)
		adminRoutes.GET("/apps/:id/email-servers", adminHandler.ListEmailServerConfigsByApp)

		// Email server config CRUD (config-level, multi-config)
		adminRoutes.GET("/email-servers", adminHandler.ListAllEmailServerConfigs)
		adminRoutes.GET("/email-servers/:id", adminHandler.GetEmailServerConfigByID)
		adminRoutes.POST("/email-servers", adminHandler.CreateEmailServerConfig)
		adminRoutes.PUT("/email-servers/:id", adminHandler.UpdateEmailServerConfigByID)
		adminRoutes.DELETE("/email-servers/:id", adminHandler.DeleteEmailServerConfigByID)
		adminRoutes.POST("/email-servers/:id/test", adminHandler.SendTestEmailByConfigID)

		// Email type CRUD & send email
		adminRoutes.POST("/email-types", adminHandler.CreateEmailType)
		adminRoutes.PUT("/email-types/:id", adminHandler.UpdateEmailType)
		adminRoutes.DELETE("/email-types/:id", adminHandler.DeleteEmailType)
		adminRoutes.POST("/apps/:id/send-email", adminHandler.SendCustomEmail)
	}

	// App API routes (protected by per-application API key)
	// These expose a subset of admin functionality for app-level access.
	// Requires both X-App-ID and X-App-API-Key headers.
	// The app key must be bound to the same application as X-App-ID,
	// and AppRouteGuardMiddleware ensures the URL :id matches X-App-ID.
	appRoutes := r.Group("/app/:id")
	appRoutes.Use(middleware.AppApiKeyMiddleware(adminRepo))
	appRoutes.Use(middleware.AppRouteGuardMiddleware())
	{
		// Read-only: SMTP configuration
		appRoutes.GET("/email-config", adminHandler.GetEmailServerConfig)
		appRoutes.GET("/email-servers", adminHandler.ListEmailServerConfigsByApp)

		// Send emails
		appRoutes.POST("/email-test", adminHandler.SendTestEmail)
		appRoutes.POST("/send-email", adminHandler.SendCustomEmail)
	}

	// GUI routes (Admin web interface)
	gui := r.Group("/gui")
	{
		// Static assets (no auth required)
		gui.StaticFS("/static", static.HTTPFileSystem())

		// Login page and form submission (no auth required)
		gui.GET("/login", guiHandler.LoginPage)
		gui.POST("/login", middleware.LoginRateLimitMiddleware(), guiHandler.LoginSubmit)

		// Authenticated GUI routes
		guiAuth := gui.Group("/")
		guiAuth.Use(middleware.GUIAuthMiddleware(accountService))
		guiAuth.Use(middleware.CSRFMiddleware(accountService))
		{
			guiAuth.GET("/", guiHandler.Dashboard)
			guiAuth.GET("/dashboard/stats", guiHandler.DashboardStats)
			guiAuth.GET("/dashboard/activity", guiHandler.DashboardActivity)
			guiAuth.GET("/logout", guiHandler.Logout)

			// Tenant management
			guiAuth.GET("/tenants", guiHandler.TenantPage)
			guiAuth.GET("/tenants/list", guiHandler.TenantList)
			guiAuth.GET("/tenants/new", guiHandler.TenantCreateForm)
			guiAuth.POST("/tenants", guiHandler.TenantCreate)
			guiAuth.GET("/tenants/form-cancel", guiHandler.TenantFormCancel)
			guiAuth.GET("/tenants/:id/edit", guiHandler.TenantEditForm)
			guiAuth.PUT("/tenants/:id", guiHandler.TenantUpdate)
			guiAuth.GET("/tenants/:id/delete", guiHandler.TenantDeleteConfirm)
			guiAuth.DELETE("/tenants/:id", guiHandler.TenantDelete)

			// Application management
			guiAuth.GET("/applications", guiHandler.AppPage)
			guiAuth.GET("/applications/list", guiHandler.AppList)
			guiAuth.GET("/applications/new", guiHandler.AppCreateForm)
			guiAuth.POST("/applications", guiHandler.AppCreate)
			guiAuth.GET("/applications/form-cancel", guiHandler.AppFormCancel)
			guiAuth.GET("/applications/:id/edit", guiHandler.AppEditForm)
			guiAuth.PUT("/applications/:id", guiHandler.AppUpdate)
			guiAuth.GET("/applications/:id/delete", guiHandler.AppDeleteConfirm)
			guiAuth.DELETE("/applications/:id", guiHandler.AppDelete)

			// OAuth config management
			guiAuth.GET("/oauth", guiHandler.OAuthPage)
			guiAuth.GET("/oauth/list", guiHandler.OAuthList)
			guiAuth.GET("/oauth/new", guiHandler.OAuthCreateForm)
			guiAuth.POST("/oauth", guiHandler.OAuthCreate)
			guiAuth.GET("/oauth/form-cancel", guiHandler.OAuthFormCancel)
			guiAuth.GET("/oauth/:id/edit", guiHandler.OAuthEditForm)
			guiAuth.PUT("/oauth/:id", guiHandler.OAuthUpdate)
			guiAuth.GET("/oauth/:id/delete", guiHandler.OAuthDeleteConfirm)
			guiAuth.DELETE("/oauth/:id", guiHandler.OAuthDelete)
			guiAuth.PUT("/oauth/:id/toggle", guiHandler.OAuthToggleEnabled)

			// User management
			guiAuth.GET("/users", guiHandler.UserPage)
			guiAuth.GET("/users/list", guiHandler.UserList)
			guiAuth.GET("/users/:id", guiHandler.UserDetail)
			guiAuth.PUT("/users/:id/toggle", guiHandler.UserToggleActive)

			// Activity logs viewer
			guiAuth.GET("/logs", guiHandler.LogsPage)
			guiAuth.GET("/logs/list", guiHandler.LogList)
			guiAuth.GET("/logs/:id", guiHandler.LogDetail)

			// API key management
			guiAuth.GET("/api-keys", guiHandler.ApiKeysPage)
			guiAuth.GET("/api-keys/list", guiHandler.ApiKeyList)
			guiAuth.GET("/api-keys/new", guiHandler.ApiKeyCreateForm)
			guiAuth.POST("/api-keys", guiHandler.ApiKeyCreate)
			guiAuth.GET("/api-keys/form-cancel", guiHandler.ApiKeyFormCancel)
			guiAuth.GET("/api-keys/:id/revoke", guiHandler.ApiKeyRevokeConfirm)
			guiAuth.PUT("/api-keys/:id/revoke", guiHandler.ApiKeyRevoke)
			guiAuth.GET("/api-keys/:id/delete", guiHandler.ApiKeyDeleteConfirm)
			guiAuth.DELETE("/api-keys/:id", guiHandler.ApiKeyDelete)

			// Settings management
			guiAuth.GET("/settings", guiHandler.SettingsPage)
			guiAuth.GET("/settings/info", guiHandler.SettingsInfo)
			guiAuth.GET("/settings/section/:category", guiHandler.SettingsSection)
			guiAuth.PUT("/settings/:key", guiHandler.SettingUpdate)
			guiAuth.DELETE("/settings/:key", guiHandler.SettingReset)

			// Email server management
			guiAuth.GET("/email-servers", guiHandler.EmailServersPage)
			guiAuth.GET("/email-servers/list", guiHandler.EmailServerList)
			guiAuth.GET("/email-servers/new", guiHandler.EmailServerCreateForm)
			guiAuth.POST("/email-servers", guiHandler.EmailServerCreate)
			guiAuth.GET("/email-servers/form-cancel", guiHandler.EmailServerFormCancel)
			guiAuth.GET("/email-servers/:id/edit", guiHandler.EmailServerEditForm)
			guiAuth.PUT("/email-servers/:id", guiHandler.EmailServerUpdate)
			guiAuth.GET("/email-servers/:id/delete", guiHandler.EmailServerDeleteConfirm)
			guiAuth.DELETE("/email-servers/:id", guiHandler.EmailServerDelete)
			guiAuth.POST("/email-servers/:id/test", guiHandler.EmailServerSendTest)

			// Email template management
			guiAuth.GET("/email-templates", guiHandler.EmailTemplatesPage)
			guiAuth.GET("/email-templates/list", guiHandler.EmailTemplateList)
			guiAuth.GET("/email-templates/new", guiHandler.EmailTemplateCreateForm)
			guiAuth.POST("/email-templates", guiHandler.EmailTemplateCreate)
			guiAuth.GET("/email-templates/form-cancel", guiHandler.EmailTemplateFormCancel)
			guiAuth.GET("/email-templates/:id/edit", guiHandler.EmailTemplateEditForm)
			guiAuth.PUT("/email-templates/:id", guiHandler.EmailTemplateUpdate)
			guiAuth.GET("/email-templates/:id/delete", guiHandler.EmailTemplateDeleteConfirm)
			guiAuth.DELETE("/email-templates/:id", guiHandler.EmailTemplateDelete)
			guiAuth.POST("/email-templates/preview", guiHandler.EmailTemplatePreview)
			guiAuth.GET("/email-templates/:id/reset", guiHandler.EmailTemplateResetConfirm)
			guiAuth.POST("/email-templates/:id/reset", guiHandler.EmailTemplateReset)

			// Email types management
			guiAuth.GET("/email-types", guiHandler.EmailTypesPage)
			guiAuth.GET("/email-types/list", guiHandler.EmailTypeList)
			guiAuth.GET("/email-types/new", guiHandler.EmailTypeCreateForm)
			guiAuth.POST("/email-types", guiHandler.EmailTypeCreate)
			guiAuth.GET("/email-types/form-cancel", guiHandler.EmailTypeFormCancel)
			guiAuth.GET("/email-types/:id/edit", guiHandler.EmailTypeEditForm)
			guiAuth.PUT("/email-types/:id", guiHandler.EmailTypeUpdate)
			guiAuth.GET("/email-types/:id/delete", guiHandler.EmailTypeDeleteConfirm)
			guiAuth.DELETE("/email-types/:id", guiHandler.EmailTypeDelete)
		}
	}

	// Add Swagger UI endpoint
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Start the server
	port := viper.GetString("PORT")
	log.Printf("Server starting on port %s", port)
	if err := r.Run(fmt.Sprintf(":%s", port)); err != nil {
		log.Fatalf("Server failed to start: %v", err)
	}
}
