package main

import (
	"fmt"
	"log"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/google/uuid"
	"github.com/joho/godotenv"
	"github.com/spf13/viper"

	_ "github.com/gjovanovicst/auth_api/docs" // docs is generated by Swag CLI
	"github.com/gjovanovicst/auth_api/internal/admin"
	"github.com/gjovanovicst/auth_api/internal/bruteforce"
	"github.com/gjovanovicst/auth_api/internal/database"
	"github.com/gjovanovicst/auth_api/internal/email"
	"github.com/gjovanovicst/auth_api/internal/geoip"
	"github.com/gjovanovicst/auth_api/internal/health"
	logService "github.com/gjovanovicst/auth_api/internal/log"
	"github.com/gjovanovicst/auth_api/internal/middleware"
	"github.com/gjovanovicst/auth_api/internal/oidc"
	"github.com/gjovanovicst/auth_api/internal/rbac"
	"github.com/gjovanovicst/auth_api/internal/redis"
	"github.com/gjovanovicst/auth_api/internal/session"
	"github.com/gjovanovicst/auth_api/internal/sms"
	"github.com/gjovanovicst/auth_api/internal/social"
	ssopkg "github.com/gjovanovicst/auth_api/internal/sso"
	"github.com/gjovanovicst/auth_api/internal/twofa"
	"github.com/gjovanovicst/auth_api/internal/user"
	passkey "github.com/gjovanovicst/auth_api/internal/webauthn"
	"github.com/gjovanovicst/auth_api/internal/webhook"
	"github.com/gjovanovicst/auth_api/web"
	"github.com/gjovanovicst/auth_api/web/static"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title           Authentication and Authorization API
// @version         1.1.0
// @description     This is a sample authentication and authorization API built with Go and Gin.
// @termsOfService  http://swagger.io/terms/

// @contact.name   API Support
// @contact.url    http://www.swagger.io/support
// @contact.email  support@swagger.io

// @license.name  Apache 2.0
// @license.url   http://www.apache.org/licenses/LICENSE-2.0.html

// @host      localhost:8080
// @BasePath  /

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization
// @description Type "Bearer" + your JWT token

// @securityDefinitions.apikey AppID
// @in header
// @name X-App-ID
// @description The UUID of the application context

// @securityDefinitions.apikey AdminApiKey
// @in header
// @name X-Admin-API-Key
// @description Admin API Key for protected admin routes

// @securityDefinitions.apikey AppApiKey
// @in header
// @name X-App-API-Key
// @description Per-application API Key for app-scoped routes

func main() {
	// Load environment variables from .env file
	if err := godotenv.Load(); err != nil {
		log.Println("No .env file found, relying on environment variables")
	}

	// Initialize Viper for configuration management
	viper.AutomaticEnv() // Read environment variables
	viper.SetDefault("PORT", "8080")
	viper.SetDefault("ACCESS_TOKEN_EXPIRATION_MINUTES", 15)
	viper.SetDefault("REFRESH_TOKEN_EXPIRATION_HOURS", 720)
	// OIDC provider configuration
	viper.SetDefault("OIDC_ENABLED", false)
	viper.SetDefault("OIDC_DEFAULT_APP_ID", "00000000-0000-0000-0000-000000000001")
	viper.SetDefault("PUBLIC_URL", "http://localhost:8080")
	viper.SetDefault("FRONTEND_URL", "http://localhost:5173")
	// CORS configuration defaults (all previously hardcoded values, now configurable via env or admin settings)
	viper.SetDefault("CORS_ALLOWED_ORIGINS", "http://localhost:3000,http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:8080")
	viper.SetDefault("CORS_ALLOWED_METHODS", "GET,POST,PUT,DELETE,OPTIONS,HEAD")
	viper.SetDefault("CORS_ALLOWED_HEADERS", "Origin,Content-Type,Content-Length,Accept-Encoding,X-CSRF-Token,Authorization,Accept,Cache-Control,X-Requested-With,X-App-ID")
	viper.SetDefault("CORS_EXPOSE_HEADERS", "Content-Length,Access-Control-Allow-Origin,Access-Control-Allow-Headers,Content-Type")
	viper.SetDefault("CORS_MAX_AGE_HOURS", 12)
	viper.SetDefault("CORS_ALLOW_CREDENTIALS", true)
	viper.SetDefault("OIDC_ID_TOKEN_EXPIRATION_MINUTES", 60)
	viper.SetDefault("OIDC_AUTH_CODE_EXPIRATION_MINUTES", 10)
	// Trusted device cookie SameSite policy.
	// "none"   = cross-origin deployments (Auth API and frontend on different domains — e.g. Planora).
	//            SameSite=None requires Secure=true, which is enforced automatically.
	// "lax"    = same-site subdomains (e.g. auth.example.com + app.example.com).
	// "strict" = same-origin only (Auth API and frontend on the identical domain).
	// Default is "none" to support cross-origin setups out of the box.
	viper.SetDefault("TRUSTED_DEVICE_COOKIE_SAMESITE", "none")

	// Connect to database
	database.ConnectDatabase()

	// Connect to Redis
	redis.ConnectRedis()

	// Run database migrations
	database.MigrateDatabase()

	// Initialize GeoIP service (graceful degradation if not configured)
	geoIPService := geoip.NewService(viper.GetString("GEOIP_DB_PATH"))

	// Initialize Anomaly Detector (uses GeoIP if available)
	anomalyDetector := logService.NewAnomalyDetector(database.DB, geoIPService)

	// Initialize Brute-Force Protection Service (account lockout, progressive delays, CAPTCHA)
	bruteForceService := bruteforce.NewService(database.DB)

	// Initialize Activity Log Service
	logSvc := logService.InitializeLogService(database.DB, anomalyDetector)

	// Initialize IP Rule infrastructure
	ipRuleRepo := geoip.NewIPRuleRepository(database.DB)
	ipRuleEvaluator := geoip.NewIPRuleEvaluator(ipRuleRepo, geoIPService)

	// Initialize Activity Log Cleanup Service
	cleanupService := logService.InitializeCleanupService(database.DB)
	if cleanupService != nil {
		// Ensure graceful shutdown of cleanup service
		defer cleanupService.Shutdown()
	}

	// Initialize Services and Handlers
	userRepo := user.NewRepository(database.DB)
	socialRepo := social.NewRepository(database.DB)
	logRepo := logService.NewRepository(database.DB)
	emailRepo := email.NewRepository(database.DB)
	emailService := email.NewService(emailRepo, database.DB)
	rbacRepo := rbac.NewRepository(database.DB)
	rbacService := rbac.NewService(rbacRepo)
	rbacHandler := rbac.NewHandler(rbacService)
	userService := user.NewService(userRepo, emailService, database.DB)
	userService.LookupRoles = rbacService.GetUserRoleNames
	userService.AssignDefaultRole = rbacService.AssignDefaultRole
	sessionService := session.NewService()
	userService.SessionService = sessionService
	socialService := social.NewService(userRepo, socialRepo)
	socialService.LookupRoles = rbacService.GetUserRoleNames
	socialService.AssignDefaultRole = rbacService.AssignDefaultRole
	socialService.SessionService = sessionService
	twofaService := twofa.NewService(userRepo, database.DB, emailService)
	logQueryService := logService.NewQueryService(logRepo)

	// Initialize SMS sender (graceful degradation if not configured)
	smsSender := sms.NewSenderFromConfig()

	// Initialize Trusted Device Repository
	trustedDeviceRepo := twofa.NewTrustedDeviceRepository(database.DB)

	// Initialize Webhook Service
	webhookRepo := webhook.NewRepository(database.DB)
	webhookService := webhook.NewService(webhookRepo)
	defer webhookService.Shutdown()
	webhookHandler := webhook.NewHandler(webhookService)

	// Wire WebhookService into domain services
	userService.WebhookService = webhookService
	twofaService.WebhookService = webhookService
	socialService.WebhookService = webhookService
	// Wire SMS sender and trusted device repo into twofa service
	twofaService.SMSSender = smsSender
	twofaService.TrustedDeviceRepo = trustedDeviceRepo
	// Wire SMS sender into user service so SMS 2FA codes are auto-sent on password login
	userService.SMSSender = smsSender
	userHandler := user.NewHandler(userService)
	socialHandler := social.NewHandler(socialService)
	// Wire twofa service into social handler so SMS 2FA codes are auto-sent on social login
	socialHandler.TwoFAService = twofaService
	// Wire trusted device validation callback into social handler
	socialHandler.ValidateTrustedDevice = func(plainToken string) (uuid.UUID, uuid.UUID, bool) {
		device, appErr := twofaService.ValidateTrustedDevice(plainToken)
		if appErr != nil {
			return uuid.Nil, uuid.Nil, false
		}
		return device.UserID, device.AppID, true
	}
	twofaHandler := twofa.NewHandler(twofaService)
	twofaHandler.LookupRoles = rbacService.GetUserRoleNames
	twofaHandler.SessionService = sessionService
	twofaHandler.AssignDefaultRole = rbacService.AssignDefaultRole
	// Wire trusted device repo into twofa handler
	twofaHandler.TrustedDeviceRepo = trustedDeviceRepo
	// Wire DB for per-app token TTL overrides
	twofaHandler.DB = database.DB
	// Wire trusted device validation callback into user handler (avoids circular import)
	userHandler.ValidateTrustedDevice = func(plainToken string) (uuid.UUID, uuid.UUID, bool) {
		device, appErr := twofaService.ValidateTrustedDevice(plainToken)
		if appErr != nil {
			return uuid.Nil, uuid.Nil, false
		}
		return device.UserID, device.AppID, true
	}
	logHandler := logService.NewHandler(logQueryService)
	sessionHandler := session.NewHandler(sessionService)
	adminRepo := admin.NewRepository(database.DB)
	adminHandler := admin.NewHandler(adminRepo, emailService)

	// Initialize Health & Metrics Handler
	smtpAddr := health.ResolveSMTPAddr(database.DB)
	healthHandler := health.NewHandler(database.DB, redis.Rdb, smtpAddr)

	// Initialize WebAuthn/Passkey Services and Handler
	webauthnRepo := passkey.NewRepository(database.DB)
	webauthnService := passkey.NewService(webauthnRepo, userRepo, database.DB)
	webauthnHandler := passkey.NewHandler(webauthnService)
	webauthnHandler.LookupRoles = rbacService.GetUserRoleNames
	webauthnHandler.SessionService = sessionService
	webauthnHandler.AssignDefaultRole = rbacService.AssignDefaultRole
	// Wire DB for per-app token TTL overrides
	webauthnHandler.DB = database.DB

	// Initialize Admin GUI Services and Handler
	accountRepo := admin.NewAccountRepository(database.DB)
	accountService := admin.NewAccountService(accountRepo, emailService)
	dashboardService := admin.NewDashboardService(database.DB)
	settingsRepo := admin.NewSettingsRepository(database.DB)
	settingsService := admin.NewSettingsService(settingsRepo)
	guiHandler := admin.NewGUIHandler(accountService, dashboardService, adminRepo, settingsService, emailService, rbacService, webauthnService)

	// Initialize SSO Handler
	ssoHandler := ssopkg.NewHandler(adminRepo, userRepo, sessionService, database.DB)
	ssoHandler.LookupRoles = rbacService.GetUserRoleNames

	// Wire SSO global logout: when a user logs out of one app in a session group,
	// their sessions in all other apps of the group are revoked (only when GlobalLogout=true).
	userService.GroupLogoutFunc = func(appID, userEmail string) {
		group, err := adminRepo.GetSessionGroupForApp(appID)
		if err != nil || group == nil || !group.GlobalLogout {
			return
		}
		appIDs, err := adminRepo.GetAppsInSessionGroup(group.ID.String())
		if err != nil {
			return
		}
		for _, otherAppID := range appIDs {
			if otherAppID == appID {
				continue
			}
			targetUser, err := userRepo.GetUserByEmail(otherAppID, userEmail)
			if err != nil || targetUser == nil {
				continue
			}
			if appErr := sessionService.RevokeAllUserSessions(otherAppID, targetUser.ID.String()); appErr != nil {
				log.Printf("[SSO] Warning: failed to revoke sessions for user %s in app %s: %v", userEmail, otherAppID, appErr.Message)
			}
		}
	}

	// Wire SettingsService resolver into twofa handler so the TRUSTED_DEVICE_COOKIE_SAMESITE
	// setting is resolved via the 3-tier priority (env > DB > default), allowing the admin GUI
	// to control it without a process restart.
	twofaHandler.SettingResolver = settingsService.GetResolvedValue

	// Wire admin lookup for passkey discoverable login
	webauthnService.AdminLookup = accountRepo.GetByID

	// Wire WebhookService into admin GUI handler
	guiHandler.WebhookService = webhookService
	webauthnHandler.WebhookService = webhookService

	// Initialize OIDC Provider (enabled via OIDC_ENABLED=true)
	var oidcHandler *oidc.Handler
	if viper.GetBool("OIDC_ENABLED") {
		oidcRepo := oidc.NewRepository(database.DB)
		oidcService := oidc.NewService(oidcRepo, rbacService.GetUserRoleNames)
		oidcHandler = oidc.NewHandler(oidcService, oidcRepo)
		guiHandler.OIDCService = oidcService
		// Wire OIDC RP-initiated logout group logout: revoke peer-app JWT sessions
		// for the logging-out user, mirroring userService.GroupLogoutFunc.
		oidcHandler.GroupLogoutFunc = func(appID, userEmail string) {
			group, err := adminRepo.GetSessionGroupForApp(appID)
			if err != nil || group == nil || !group.GlobalLogout {
				return
			}
			appIDs, err := adminRepo.GetAppsInSessionGroup(group.ID.String())
			if err != nil {
				return
			}
			for _, otherAppID := range appIDs {
				if otherAppID == appID {
					continue
				}
				targetUser, err := userRepo.GetUserByEmail(otherAppID, userEmail)
				if err != nil || targetUser == nil {
					continue
				}
				if appErr := sessionService.RevokeAllUserSessions(otherAppID, targetUser.ID.String()); appErr != nil {
					log.Printf("[OIDC] Warning: failed to revoke sessions for user %s in app %s: %v", userEmail, otherAppID, appErr.Message)
				}
			}
		}
		// Fix #10: Run an initial cleanup immediately on startup so stale codes
		// from before the last restart are purged without waiting a full hour.
		go func() {
			if err := oidcRepo.DeleteExpiredAuthCodes(); err != nil {
				log.Printf("[OIDC] startup cleanup of expired auth codes failed: %v", err)
			}
			ticker := time.NewTicker(1 * time.Hour)
			defer ticker.Stop()
			for range ticker.C {
				if err := oidcRepo.DeleteExpiredAuthCodes(); err != nil {
					log.Printf("[OIDC] failed to delete expired auth codes: %v", err)
				}
			}
		}()
	}

	// Wire IP rule evaluator and anomaly detector on login handlers
	userHandler.IPRuleEvaluator = ipRuleEvaluator
	userHandler.AnomalyDetector = anomalyDetector
	socialHandler.IPRuleEvaluator = ipRuleEvaluator
	socialHandler.AnomalyDetector = anomalyDetector
	twofaHandler.IPRuleEvaluator = ipRuleEvaluator
	twofaHandler.AnomalyDetector = anomalyDetector
	webauthnHandler.IPRuleEvaluator = ipRuleEvaluator
	webauthnHandler.AnomalyDetector = anomalyDetector

	// Wire brute-force protection service on login handlers
	userHandler.BruteForceService = bruteForceService
	guiHandler.BruteForceService = bruteForceService

	// Wire IP rule management on admin handlers
	adminHandler.IPRuleRepo = ipRuleRepo
	adminHandler.IPRuleEvaluator = ipRuleEvaluator
	adminHandler.GeoIPService = geoIPService
	adminHandler.TrustedDeviceRepo = trustedDeviceRepo
	guiHandler.IPRuleRepo = ipRuleRepo
	guiHandler.IPRuleEvaluator = ipRuleEvaluator
	guiHandler.GeoIPService = geoIPService
	guiHandler.TrustedDeviceRepo = trustedDeviceRepo

	// Wire health handler into admin GUI for the monitoring page
	guiHandler.HealthHandler = healthHandler

	// Wire anomaly notification callback: sends emails when anomalies are detected
	logSvc.SetAnomalyCallback(func(appID, userID uuid.UUID, userEmail string, result logService.AnomalyResult) {
		if result.NotificationDetails == nil {
			return
		}
		nd := result.NotificationDetails
		switch result.NotificationType {
		case "new_device_login":
			if err := emailService.SendNewDeviceLoginEmail(appID, userEmail, &userID,
				nd.IPAddress, nd.Location, nd.Device, nd.LoginTime); err != nil {
				log.Printf("Anomaly notification (new_device_login) failed for user %s: %v", userEmail, err)
			}
		case "suspicious_activity":
			if err := emailService.SendSuspiciousActivityEmail(appID, userEmail, &userID,
				nd.IPAddress, nd.Location, nd.Device, nd.LoginTime, nd.AlertType, nd.Details); err != nil {
				log.Printf("Anomaly notification (suspicious_activity) failed for user %s: %v", userEmail, err)
			}
		}
	})

	// Initialize and start the API key expiry notification service
	apiKeyNotificationSvc := admin.NewApiKeyNotificationService(adminRepo, emailService)
	apiKeyNotificationSvc.Start()
	defer apiKeyNotificationSvc.Shutdown()

	// Setup Gin Router
	r := gin.Default()

	// Initialize template renderer for GUI
	renderer, err := web.NewRenderer()
	if err != nil {
		log.Fatalf("Failed to initialize template renderer: %v", err)
	}
	r.HTMLRender = renderer

	// Add security headers middleware (before CORS so headers are always set)
	r.Use(middleware.SecurityHeadersMiddleware())

	// Add CORS middleware
	r.Use(middleware.CORSMiddleware())
	r.Use(middleware.AppIDMiddleware())

	// Instrument all requests with Prometheus metrics
	r.Use(health.PrometheusMiddleware())

	// Public routes (with rate limiting)
	public := r.Group("/")
	{
		public.POST("/register", middleware.APIRegisterRateLimit(), userHandler.Register)
		public.POST("/login", middleware.APILoginRateLimit(), userHandler.Login)
		public.POST("/refresh-token", middleware.APIRefreshTokenRateLimit(), userHandler.RefreshToken)
		public.POST("/forgot-password", middleware.APIForgotPasswordRateLimit(), userHandler.ForgotPassword)
		public.POST("/reset-password", middleware.APIResetPasswordRateLimit(), userHandler.ResetPassword)
		public.GET("/verify-email", userHandler.VerifyEmail)
		public.POST("/resend-verification", middleware.APIResendVerificationRateLimit(), userHandler.ResendVerification)
		// 2FA login verification (public because it needs temp token)
		public.POST("/2fa/login-verify", middleware.API2FAVerifyRateLimit(), twofaHandler.VerifyLogin)
		// 2FA email code resend (public because it needs temp token during login)
		public.POST("/2fa/email/resend", middleware.API2FAVerifyRateLimit(), twofaHandler.ResendEmail2FACode)
		// 2FA SMS code resend (public because it needs temp token during login)
		public.POST("/2fa/sms/resend", middleware.API2FAVerifyRateLimit(), twofaHandler.ResendSMS2FACode)
		// 2FA backup email code resend (public because it needs temp token during login)
		public.POST("/2fa/backup-email/resend", middleware.API2FAVerifyRateLimit(), twofaHandler.ResendBackupEmail2FACode)
		// Backup email verification (public — token sent by email, no auth required)
		public.GET("/2fa/backup-email/verify", twofaHandler.VerifyBackupEmail)
		// 2FA available methods (public so login UI can show method options)
		public.GET("/2fa/methods", twofaHandler.GetAvailableMethods)

		// Passkey 2FA login (public because it needs temp token)
		public.POST("/2fa/passkey/begin", middleware.APIPasskey2FARateLimit(), webauthnHandler.BeginPasskey2FA)
		public.POST("/2fa/passkey/finish", middleware.APIPasskey2FARateLimit(), webauthnHandler.FinishPasskey2FA)

		// Passwordless passkey login (public)
		public.POST("/passkey/login/begin", middleware.APIPasskeyLoginRateLimit(), webauthnHandler.BeginPasswordlessLogin)
		public.POST("/passkey/login/finish", middleware.APIPasskeyLoginRateLimit(), webauthnHandler.FinishPasswordlessLogin)

		// Magic link passwordless login (public)
		public.POST("/magic-link/request", middleware.APIMagicLinkRateLimit(), userHandler.RequestMagicLink)
		public.POST("/magic-link/verify", middleware.APIMagicLinkRateLimit(), userHandler.VerifyMagicLink)

		// Public app login configuration (no auth required — used by login/register UI)
		public.GET("/app-config/:app_id", adminHandler.GetAppLoginConfig)

		// Health check (public — used by load balancers and Kubernetes probes)
		public.GET("/health", healthHandler.Health)
	}

	// Metrics endpoint (Admin API Key required — prevents exposing internal telemetry)
	metricsGroup := r.Group("", middleware.AdminAuthMiddleware(adminRepo))
	{
		metricsGroup.GET("/metrics", healthHandler.Metrics)
	}

	// Social authentication routes
	auth := r.Group("/auth")
	{
		// Google OAuth2
		auth.GET("/google/login", socialHandler.GoogleLogin)
		auth.GET("/google/callback", socialHandler.GoogleCallback)

		// Facebook OAuth2
		auth.GET("/facebook/login", socialHandler.FacebookLogin)
		auth.GET("/facebook/callback", socialHandler.FacebookCallback)

		// GitHub OAuth2
		auth.GET("/github/login", socialHandler.GithubLogin)
		auth.GET("/github/callback", socialHandler.GithubCallback)

		// Account merge confirmation (public — requires merge_token + existing password)
		auth.POST("/merge/confirm", socialHandler.MergeConfirm)

		// Account linking callbacks (public — user ID embedded in OAuth state)
		auth.GET("/google/link/callback", socialHandler.GoogleLinkCallback)
		auth.GET("/facebook/link/callback", socialHandler.FacebookLinkCallback)
		auth.GET("/github/link/callback", socialHandler.GithubLinkCallback)
	}

	// Account linking initiation routes (require JWT authentication)
	authLink := r.Group("/auth")
	authLink.Use(middleware.AuthMiddleware())
	{
		authLink.GET("/google/link", socialHandler.GoogleLink)
		authLink.GET("/facebook/link", socialHandler.FacebookLink)
		authLink.GET("/github/link", socialHandler.GithubLink)
	}

	// Protected routes (require JWT authentication)
	protected := r.Group("/")
	protected.Use(middleware.AuthMiddleware())
	{
		// User profile routes (require user:read / user:write / user:delete)
		protected.GET("/profile", middleware.AuthorizePermission(rbacService, "user", "read"), userHandler.GetProfile)
		protected.PUT("/profile", middleware.AuthorizePermission(rbacService, "user", "write"), userHandler.UpdateProfile)
		protected.DELETE("/profile", middleware.AuthorizePermission(rbacService, "user", "delete"), userHandler.DeleteAccount)
		protected.PUT("/profile/email", middleware.AuthorizePermission(rbacService, "user", "write"), userHandler.UpdateEmail)
		protected.PUT("/profile/password", middleware.AuthorizePermission(rbacService, "user", "write"), userHandler.UpdatePassword)
		protected.POST("/profile/set-password", middleware.AuthorizePermission(rbacService, "user", "write"), userHandler.SetPassword)

		// Social account management routes
		protected.GET("/profile/social-accounts", middleware.AuthorizePermission(rbacService, "user", "read"), socialHandler.ListSocialAccounts)
		protected.DELETE("/profile/social-accounts/:id", middleware.AuthorizePermission(rbacService, "user", "write"), socialHandler.UnlinkSocialAccount)

		// Auth routes (no extra permission needed — auth is inherent)
		protected.GET("/auth/validate", userHandler.ValidateToken)
		protected.POST("/logout", userHandler.Logout)

		// 2FA management routes (require settings:write — managing own security settings)
		protected.POST("/2fa/generate", middleware.AuthorizePermission(rbacService, "settings", "write"), twofaHandler.Generate2FA)
		protected.POST("/2fa/verify-setup", middleware.AuthorizePermission(rbacService, "settings", "write"), twofaHandler.VerifySetup)
		protected.POST("/2fa/enable", middleware.AuthorizePermission(rbacService, "settings", "write"), twofaHandler.Enable2FA)
		protected.POST("/2fa/disable", middleware.AuthorizePermission(rbacService, "settings", "write"), twofaHandler.Disable2FA)
		protected.POST("/2fa/recovery-codes", middleware.AuthorizePermission(rbacService, "settings", "write"), twofaHandler.GenerateRecoveryCodes)
		// Email 2FA routes
		protected.POST("/2fa/email/enable", middleware.AuthorizePermission(rbacService, "settings", "write"), twofaHandler.EnableEmail2FA)

		// SMS 2FA routes
		protected.POST("/2fa/sms/enable", middleware.AuthorizePermission(rbacService, "settings", "write"), twofaHandler.EnableSMS2FA)

		// Backup email 2FA routes
		protected.POST("/2fa/backup-email", middleware.AuthorizePermission(rbacService, "settings", "write"), twofaHandler.AddBackupEmail)
		protected.DELETE("/2fa/backup-email", middleware.AuthorizePermission(rbacService, "settings", "write"), twofaHandler.RemoveBackupEmail)
		protected.GET("/2fa/backup-email/status", middleware.AuthorizePermission(rbacService, "settings", "read"), twofaHandler.BackupEmailStatus)
		protected.POST("/2fa/backup-email/enable", middleware.AuthorizePermission(rbacService, "settings", "write"), twofaHandler.EnableBackupEmail2FA)
		protected.POST("/2fa/backup-email/disable", middleware.AuthorizePermission(rbacService, "settings", "write"), twofaHandler.DisableBackupEmail2FA)

		// Phone management routes
		protected.POST("/phone", middleware.AuthorizePermission(rbacService, "settings", "write"), twofaHandler.AddPhone)
		protected.POST("/phone/verify", middleware.AuthorizePermission(rbacService, "settings", "write"), twofaHandler.VerifyPhone)
		protected.DELETE("/phone", middleware.AuthorizePermission(rbacService, "settings", "write"), twofaHandler.RemovePhone)
		protected.GET("/phone/status", middleware.AuthorizePermission(rbacService, "settings", "read"), twofaHandler.PhoneStatus)

		// Trusted device management routes
		protected.GET("/2fa/trusted-devices", middleware.AuthorizePermission(rbacService, "settings", "read"), twofaHandler.ListTrustedDevices)
		protected.DELETE("/2fa/trusted-devices/:id", middleware.AuthorizePermission(rbacService, "settings", "write"), twofaHandler.RevokeTrustedDevice)
		protected.DELETE("/2fa/trusted-devices", middleware.AuthorizePermission(rbacService, "settings", "write"), twofaHandler.RevokeAllTrustedDevices)

		// Passkey management routes (require settings:write)
		protected.POST("/passkey/register/begin", middleware.AuthorizePermission(rbacService, "settings", "write"), webauthnHandler.BeginRegistration)
		protected.POST("/passkey/register/finish", middleware.AuthorizePermission(rbacService, "settings", "write"), webauthnHandler.FinishRegistration)
		protected.GET("/passkeys", middleware.AuthorizePermission(rbacService, "settings", "read"), webauthnHandler.ListCredentials)
		protected.PUT("/passkeys/:id", middleware.AuthorizePermission(rbacService, "settings", "write"), webauthnHandler.RenameCredential)
		protected.DELETE("/passkeys/:id", middleware.AuthorizePermission(rbacService, "settings", "write"), webauthnHandler.DeleteCredential)

		// Activity log routes (require log:read)
		protected.GET("/activity-logs", middleware.AuthorizePermission(rbacService, "log", "read"), logHandler.GetUserActivityLogs)
		protected.GET("/activity-logs/event-types", middleware.AuthorizePermission(rbacService, "log", "read"), logHandler.GetEventTypes)
		protected.GET("/activity-logs/export", middleware.AuthorizePermission(rbacService, "log", "read"), logHandler.ExportUserActivityLogs)
		protected.GET("/activity-logs/:id", middleware.AuthorizePermission(rbacService, "log", "read"), logHandler.GetActivityLogByID)

		// Session management routes
		protected.GET("/sessions", sessionHandler.ListSessions)
		protected.DELETE("/sessions/:id", sessionHandler.RevokeSession)
		protected.DELETE("/sessions", sessionHandler.RevokeAllSessions)
	}

	// SSO routes
	// Public exchange endpoint — target app identified by X-App-ID header.
	ssoPublic := r.Group("/sso")
	{
		ssoPublic.POST("/exchange", ssoHandler.Exchange)
		ssoPublic.GET("/peers", ssoHandler.GetPeers)
	}
	// Protected token issuance endpoint — requires JWT auth.
	ssoProtected := r.Group("/sso")
	ssoProtected.Use(middleware.AuthMiddleware())
	{
		ssoProtected.POST("/token", middleware.APISSORateLimit(), ssoHandler.IssueToken)
	}

	// Admin routes (protected by Admin API Key)
	adminRoutes := r.Group("/admin")
	// Remove the general AuthMiddleware and replace with AdminAuthMiddleware
	// Admin routes shouldn't require user tokens, but a specific admin key
	adminRoutes.Use(middleware.AdminAuthMiddleware(adminRepo))
	{
		adminRoutes.GET("/activity-logs", logHandler.GetAllActivityLogs)
		adminRoutes.GET("/activity-logs/export", logHandler.ExportAllActivityLogs)

		// Multi-tenancy Management
		adminRoutes.POST("/tenants", adminHandler.CreateTenant)
		adminRoutes.GET("/tenants", adminHandler.ListTenants)
		adminRoutes.POST("/apps", adminHandler.CreateApp)
		adminRoutes.GET("/apps/:id", adminHandler.GetAppDetails)
		adminRoutes.POST("/apps/:id/oauth-config", adminHandler.UpsertOAuthConfig)

		// Email management API
		adminRoutes.GET("/email-types", adminHandler.ListEmailTypes)
		adminRoutes.GET("/email-types/:code", adminHandler.GetEmailType)
		adminRoutes.GET("/email-variables", adminHandler.ListWellKnownVariables)
		adminRoutes.GET("/email-templates", adminHandler.ListEmailTemplates)
		adminRoutes.GET("/email-templates/:id", adminHandler.GetEmailTemplate)
		adminRoutes.POST("/email-templates", adminHandler.SaveEmailTemplate)
		adminRoutes.DELETE("/email-templates/:id", adminHandler.DeleteEmailTemplate)
		adminRoutes.POST("/email-templates/preview", adminHandler.PreviewEmailTemplate)
		adminRoutes.GET("/apps/:id/email-config", adminHandler.GetEmailServerConfig)
		adminRoutes.PUT("/apps/:id/email-config", adminHandler.SaveEmailServerConfig)
		adminRoutes.DELETE("/apps/:id/email-config", adminHandler.DeleteEmailServerConfig)
		adminRoutes.POST("/apps/:id/email-test", adminHandler.SendTestEmail)
		adminRoutes.GET("/apps/:id/email-servers", adminHandler.ListEmailServerConfigsByApp)

		// Email server config CRUD (config-level, multi-config)
		adminRoutes.GET("/email-servers", adminHandler.ListAllEmailServerConfigs)
		adminRoutes.GET("/email-servers/:id", adminHandler.GetEmailServerConfigByID)
		adminRoutes.POST("/email-servers", adminHandler.CreateEmailServerConfig)
		adminRoutes.PUT("/email-servers/:id", adminHandler.UpdateEmailServerConfigByID)
		adminRoutes.DELETE("/email-servers/:id", adminHandler.DeleteEmailServerConfigByID)
		adminRoutes.POST("/email-servers/:id/test", adminHandler.SendTestEmailByConfigID)

		// Email type CRUD & send email
		adminRoutes.POST("/email-types", adminHandler.CreateEmailType)
		adminRoutes.PUT("/email-types/:id", adminHandler.UpdateEmailType)
		adminRoutes.DELETE("/email-types/:id", adminHandler.DeleteEmailType)
		adminRoutes.POST("/apps/:id/send-email", adminHandler.SendCustomEmail)

		// RBAC Management
		adminRoutes.GET("/rbac/roles", rbacHandler.ListRoles)
		adminRoutes.GET("/rbac/roles/:id", rbacHandler.GetRole)
		adminRoutes.POST("/rbac/roles", rbacHandler.CreateRole)
		adminRoutes.PUT("/rbac/roles/:id", rbacHandler.UpdateRole)
		adminRoutes.DELETE("/rbac/roles/:id", rbacHandler.DeleteRole)
		adminRoutes.PUT("/rbac/roles/:id/permissions", rbacHandler.SetRolePermissions)
		adminRoutes.GET("/rbac/permissions", rbacHandler.ListPermissions)
		adminRoutes.POST("/rbac/permissions", rbacHandler.CreatePermission)
		adminRoutes.GET("/rbac/user-roles", rbacHandler.ListUserRoles)
		adminRoutes.POST("/rbac/user-roles", rbacHandler.AssignRole)
		adminRoutes.DELETE("/rbac/user-roles", rbacHandler.RevokeRole)
		adminRoutes.GET("/rbac/user-roles/user", rbacHandler.GetUserRoles)

		// IP Rule Management
		adminRoutes.GET("/apps/:id/ip-rules", adminHandler.ListIPRules)
		adminRoutes.POST("/apps/:id/ip-rules", adminHandler.CreateIPRule)
		adminRoutes.GET("/apps/:id/ip-rules/:rule_id", adminHandler.GetIPRule)
		adminRoutes.PUT("/apps/:id/ip-rules/:rule_id", adminHandler.UpdateIPRule)
		adminRoutes.DELETE("/apps/:id/ip-rules/:rule_id", adminHandler.DeleteIPRule)
		adminRoutes.POST("/apps/:id/ip-rules/check", adminHandler.CheckIPAccess)

		// Webhook Management (Admin)
		adminRoutes.GET("/webhooks", webhookHandler.AdminListEndpoints)
		adminRoutes.GET("/webhooks/apps/:app_id", webhookHandler.AdminListEndpointsByApp)
		adminRoutes.POST("/webhooks/apps/:app_id", webhookHandler.AdminCreateEndpoint)
		adminRoutes.PUT("/webhooks/:id/toggle", webhookHandler.AdminToggleEndpoint)
		adminRoutes.DELETE("/webhooks/:id", webhookHandler.AdminDeleteEndpoint)
		adminRoutes.GET("/webhooks/:id/deliveries", webhookHandler.AdminListDeliveriesByEndpoint)
		adminRoutes.GET("/webhooks/apps/:app_id/deliveries", webhookHandler.AdminListDeliveriesByApp)

		// User Import/Export (Admin)
		adminRoutes.GET("/users/export", adminHandler.ExportUsers)
		adminRoutes.POST("/users/import", adminHandler.ImportUsers)

		// Trusted Device Management (Admin)
		adminRoutes.GET("/users/:id/trusted-devices", adminHandler.AdminListTrustedDevices)
		adminRoutes.DELETE("/users/:id/trusted-devices/:device_id", adminHandler.AdminRevokeTrustedDevice)
		adminRoutes.DELETE("/users/:id/trusted-devices", adminHandler.AdminRevokeAllTrustedDevices)
	}

	// App API routes (protected by per-application API key)
	// These expose a subset of admin functionality for app-level access.
	// Requires both X-App-ID and X-App-API-Key headers.
	// The app key must be bound to the same application as X-App-ID,
	// and AppRouteGuardMiddleware ensures the URL :id matches X-App-ID.
	appRoutes := r.Group("/app/:id")
	appRoutes.Use(middleware.AppApiKeyMiddleware(adminRepo))
	appRoutes.Use(middleware.AppRouteGuardMiddleware())
	{
		// Read-only: SMTP configuration
		appRoutes.GET("/email-config", adminHandler.GetEmailServerConfig)
		appRoutes.GET("/email-servers", adminHandler.ListEmailServerConfigsByApp)

		// Send emails
		appRoutes.POST("/email-test", adminHandler.SendTestEmail)
		appRoutes.POST("/send-email", adminHandler.SendCustomEmail)

		// Webhook Management (App-scoped)
		appRoutes.GET("/webhooks", webhookHandler.AppListEndpoints)
		appRoutes.POST("/webhooks", webhookHandler.AppCreateEndpoint)
		appRoutes.PUT("/webhooks/:webhook_id/toggle", webhookHandler.AppToggleEndpoint)
		appRoutes.DELETE("/webhooks/:webhook_id", webhookHandler.AppDeleteEndpoint)
		appRoutes.GET("/webhooks/deliveries", webhookHandler.AppListDeliveries)
	}

	// GUI routes (Admin web interface)
	gui := r.Group("/gui")
	{
		// Static assets (no auth required)
		gui.StaticFS("/static", static.HTTPFileSystem())

		// Login page and form submission (no auth required)
		gui.GET("/login", guiHandler.LoginPage)
		gui.POST("/login", middleware.LoginRateLimitMiddleware(), guiHandler.LoginSubmit)

		// Passkey login (passwordless via discoverable credentials, no auth required)
		gui.POST("/passkey-login/begin", middleware.GUIPasskeyLoginRateLimit(), guiHandler.PasskeyLoginBegin)
		gui.POST("/passkey-login/finish", middleware.GUIPasskeyLoginRateLimit(), guiHandler.PasskeyLoginFinish)

		// Magic link login (passwordless via email link, no auth required)
		gui.POST("/magic-link-login", middleware.GUIMagicLinkRateLimit(), guiHandler.MagicLinkLoginRequest)
		gui.GET("/magic-link-login/verify", guiHandler.MagicLinkLoginVerify)

		// 2FA verification during login (no auth required — uses temp token)
		gui.GET("/2fa-verify", guiHandler.TwoFAVerifyPage)
		gui.POST("/2fa-verify", guiHandler.TwoFAVerifySubmit)
		gui.POST("/2fa-resend-email", guiHandler.TwoFAResendEmail)

		// Authenticated GUI routes
		guiAuth := gui.Group("/")
		guiAuth.Use(middleware.GUIAuthMiddleware(accountService))
		guiAuth.Use(middleware.CSRFMiddleware(accountService))
		{
			guiAuth.GET("/", guiHandler.Dashboard)
			guiAuth.GET("/dashboard/stats", guiHandler.DashboardStats)
			guiAuth.GET("/dashboard/activity", guiHandler.DashboardActivity)
			guiAuth.GET("/logout", guiHandler.Logout)

			// Tenant management
			guiAuth.GET("/tenants", guiHandler.TenantPage)
			guiAuth.GET("/tenants/list", guiHandler.TenantList)
			guiAuth.GET("/tenants/new", guiHandler.TenantCreateForm)
			guiAuth.POST("/tenants", guiHandler.TenantCreate)
			guiAuth.GET("/tenants/form-cancel", guiHandler.TenantFormCancel)
			guiAuth.GET("/tenants/:id/edit", guiHandler.TenantEditForm)
			guiAuth.PUT("/tenants/:id", guiHandler.TenantUpdate)
			guiAuth.GET("/tenants/:id/delete", guiHandler.TenantDeleteConfirm)
			guiAuth.DELETE("/tenants/:id", guiHandler.TenantDelete)

			// Application management
			guiAuth.GET("/applications", guiHandler.AppPage)
			guiAuth.GET("/applications/list", guiHandler.AppList)
			guiAuth.GET("/applications/new", guiHandler.AppCreateForm)
			guiAuth.POST("/applications", guiHandler.AppCreate)
			guiAuth.GET("/applications/form-cancel", guiHandler.AppFormCancel)
			guiAuth.GET("/applications/:id/edit", guiHandler.AppEditForm)
			guiAuth.PUT("/applications/:id", guiHandler.AppUpdate)
			guiAuth.GET("/applications/:id/delete", guiHandler.AppDeleteConfirm)
			guiAuth.DELETE("/applications/:id", guiHandler.AppDelete)

			// OAuth config management
			guiAuth.GET("/oauth", guiHandler.OAuthPage)
			guiAuth.GET("/oauth/list", guiHandler.OAuthList)
			guiAuth.GET("/oauth/new", guiHandler.OAuthCreateForm)
			guiAuth.POST("/oauth", guiHandler.OAuthCreate)
			guiAuth.GET("/oauth/form-cancel", guiHandler.OAuthFormCancel)
			guiAuth.GET("/oauth/:id/edit", guiHandler.OAuthEditForm)
			guiAuth.PUT("/oauth/:id", guiHandler.OAuthUpdate)
			guiAuth.GET("/oauth/:id/delete", guiHandler.OAuthDeleteConfirm)
			guiAuth.DELETE("/oauth/:id", guiHandler.OAuthDelete)
			guiAuth.PUT("/oauth/:id/toggle", guiHandler.OAuthToggleEnabled)

			// User management
			guiAuth.GET("/users", guiHandler.UserPage)
			guiAuth.GET("/users/list", guiHandler.UserList)
			guiAuth.GET("/users/export", guiHandler.UserExport)
			guiAuth.GET("/users/import/modal", guiHandler.UserImportModal)
			guiAuth.POST("/users/import", guiHandler.UserImport)
			guiAuth.GET("/users/:id", guiHandler.UserDetail)
			guiAuth.PUT("/users/:id/toggle", guiHandler.UserToggleActive)
			guiAuth.PUT("/users/:id/unlock", guiHandler.UserUnlock)
			guiAuth.GET("/users/social-accounts/:id/unlink", guiHandler.SocialAccountUnlinkConfirm)
			guiAuth.DELETE("/users/social-accounts/:id", guiHandler.SocialAccountUnlink)
			guiAuth.GET("/users/passkeys/:id/delete", guiHandler.PasskeyDeleteConfirm)
			guiAuth.DELETE("/users/passkeys/:id", guiHandler.PasskeyDelete)
			guiAuth.DELETE("/users/:id/trusted-devices/:device_id", guiHandler.UserRevokeTrustedDevice)
			guiAuth.DELETE("/users/:id/trusted-devices", guiHandler.UserRevokeAllTrustedDevices)

			// Activity logs viewer
			guiAuth.GET("/logs", guiHandler.LogsPage)
			guiAuth.GET("/logs/list", guiHandler.LogList)
			guiAuth.GET("/logs/export", guiHandler.LogExport)
			guiAuth.GET("/logs/:id", guiHandler.LogDetail)

			// API key management
			guiAuth.GET("/api-keys", guiHandler.ApiKeysPage)
			guiAuth.GET("/api-keys/list", guiHandler.ApiKeyList)
			guiAuth.GET("/api-keys/new", guiHandler.ApiKeyCreateForm)
			guiAuth.POST("/api-keys", guiHandler.ApiKeyCreate)
			guiAuth.GET("/api-keys/form-cancel", guiHandler.ApiKeyFormCancel)
			guiAuth.GET("/api-keys/:id/edit", guiHandler.ApiKeyEditForm)
			guiAuth.PUT("/api-keys/:id", guiHandler.ApiKeyUpdate)
			guiAuth.GET("/api-keys/:id/usage", guiHandler.ApiKeyUsagePage)
			guiAuth.GET("/api-keys/:id/revoke", guiHandler.ApiKeyRevokeConfirm)
			guiAuth.PUT("/api-keys/:id/revoke", guiHandler.ApiKeyRevoke)
			guiAuth.GET("/api-keys/:id/delete", guiHandler.ApiKeyDeleteConfirm)
			guiAuth.DELETE("/api-keys/:id", guiHandler.ApiKeyDelete)

			// Settings management
			guiAuth.GET("/settings", guiHandler.SettingsPage)
			guiAuth.GET("/settings/info", guiHandler.SettingsInfo)
			guiAuth.GET("/settings/section/:category", guiHandler.SettingsSection)
			guiAuth.PUT("/settings/:key", guiHandler.SettingUpdate)
			guiAuth.DELETE("/settings/:key", guiHandler.SettingReset)

			// System health monitoring
			guiAuth.GET("/monitoring", guiHandler.MonitoringPage)
			guiAuth.GET("/monitoring/health", guiHandler.MonitoringHealth)
			guiAuth.GET("/monitoring/metrics", guiHandler.MonitoringMetrics)

			// Email server management
			guiAuth.GET("/email-servers", guiHandler.EmailServersPage)
			guiAuth.GET("/email-servers/list", guiHandler.EmailServerList)
			guiAuth.GET("/email-servers/new", guiHandler.EmailServerCreateForm)
			guiAuth.POST("/email-servers", guiHandler.EmailServerCreate)
			guiAuth.GET("/email-servers/form-cancel", guiHandler.EmailServerFormCancel)
			guiAuth.GET("/email-servers/:id/edit", guiHandler.EmailServerEditForm)
			guiAuth.PUT("/email-servers/:id", guiHandler.EmailServerUpdate)
			guiAuth.GET("/email-servers/:id/delete", guiHandler.EmailServerDeleteConfirm)
			guiAuth.DELETE("/email-servers/:id", guiHandler.EmailServerDelete)
			guiAuth.POST("/email-servers/:id/test", guiHandler.EmailServerSendTest)

			// Email template management
			guiAuth.GET("/email-templates", guiHandler.EmailTemplatesPage)
			guiAuth.GET("/email-templates/list", guiHandler.EmailTemplateList)
			guiAuth.GET("/email-templates/new", guiHandler.EmailTemplateCreateForm)
			guiAuth.POST("/email-templates", guiHandler.EmailTemplateCreate)
			guiAuth.GET("/email-templates/form-cancel", guiHandler.EmailTemplateFormCancel)
			guiAuth.GET("/email-templates/:id/edit", guiHandler.EmailTemplateEditForm)
			guiAuth.PUT("/email-templates/:id", guiHandler.EmailTemplateUpdate)
			guiAuth.GET("/email-templates/:id/delete", guiHandler.EmailTemplateDeleteConfirm)
			guiAuth.DELETE("/email-templates/:id", guiHandler.EmailTemplateDelete)
			guiAuth.POST("/email-templates/preview", guiHandler.EmailTemplatePreview)
			guiAuth.GET("/email-templates/:id/reset", guiHandler.EmailTemplateResetConfirm)
			guiAuth.POST("/email-templates/:id/reset", guiHandler.EmailTemplateReset)

			// Email types management
			guiAuth.GET("/email-types", guiHandler.EmailTypesPage)
			guiAuth.GET("/email-types/list", guiHandler.EmailTypeList)
			guiAuth.GET("/email-types/new", guiHandler.EmailTypeCreateForm)
			guiAuth.POST("/email-types", guiHandler.EmailTypeCreate)
			guiAuth.GET("/email-types/form-cancel", guiHandler.EmailTypeFormCancel)
			guiAuth.GET("/email-types/:id/edit", guiHandler.EmailTypeEditForm)
			guiAuth.PUT("/email-types/:id", guiHandler.EmailTypeUpdate)
			guiAuth.GET("/email-types/:id/delete", guiHandler.EmailTypeDeleteConfirm)
			guiAuth.DELETE("/email-types/:id", guiHandler.EmailTypeDelete)

			// Roles management
			guiAuth.GET("/roles", guiHandler.RolesPage)
			guiAuth.GET("/roles/list", guiHandler.RoleList)
			guiAuth.GET("/roles/new", guiHandler.RoleCreateForm)
			guiAuth.POST("/roles", guiHandler.RoleCreate)
			guiAuth.GET("/roles/form-cancel", guiHandler.RoleFormCancel)
			guiAuth.GET("/roles/:id/edit", guiHandler.RoleEditForm)
			guiAuth.PUT("/roles/:id", guiHandler.RoleUpdate)
			guiAuth.GET("/roles/:id/delete", guiHandler.RoleDeleteConfirm)
			guiAuth.DELETE("/roles/:id", guiHandler.RoleDelete)
			guiAuth.GET("/roles/:id/permissions", guiHandler.RolePermissions)
			guiAuth.PUT("/roles/:id/permissions", guiHandler.RolePermissionsUpdate)

			// Permissions management
			guiAuth.GET("/permissions", guiHandler.PermissionsPage)
			guiAuth.GET("/permissions/list", guiHandler.PermissionList)
			guiAuth.GET("/permissions/new", guiHandler.PermissionCreateForm)
			guiAuth.POST("/permissions", guiHandler.PermissionCreate)
			guiAuth.GET("/permissions/form-cancel", guiHandler.PermissionFormCancel)

			// User roles management
			guiAuth.GET("/user-roles", guiHandler.UserRolesPage)
			guiAuth.GET("/user-roles/list", guiHandler.UserRoleList)
			guiAuth.GET("/user-roles/new", guiHandler.UserRoleCreateForm)
			guiAuth.POST("/user-roles", guiHandler.UserRoleCreate)
			guiAuth.PUT("/user-roles", guiHandler.UserRoleUpdate)
			guiAuth.GET("/user-roles/roles-for-app", guiHandler.UserRoleRolesForApp)
			guiAuth.GET("/user-roles/search-users", guiHandler.UserRoleSearchUsers)
			guiAuth.GET("/user-roles/revoke", guiHandler.UserRoleRevokeConfirm)
			guiAuth.DELETE("/user-roles", guiHandler.UserRoleRevoke)
			guiAuth.GET("/user-roles/form-cancel", guiHandler.UserRoleFormCancel)

			// Session management
			guiAuth.GET("/sessions", guiHandler.SessionsPage)
			guiAuth.GET("/sessions/list", guiHandler.SessionList)
			guiAuth.GET("/sessions/:app_id/:session_id/detail", guiHandler.SessionDetail)
			guiAuth.DELETE("/sessions/:app_id/:session_id", guiHandler.SessionRevoke)
			guiAuth.DELETE("/sessions/revoke-all-user", guiHandler.SessionRevokeAllForUser)
			guiAuth.GET("/users/:id/sessions", guiHandler.UserSessions)

			// IP Rule management
			guiAuth.GET("/ip-rules", guiHandler.IPRulePage)
			guiAuth.GET("/ip-rules/list", guiHandler.IPRuleList)
			guiAuth.GET("/ip-rules/new", guiHandler.IPRuleCreateForm)
			guiAuth.POST("/ip-rules", guiHandler.IPRuleCreate)
			guiAuth.GET("/ip-rules/form-cancel", guiHandler.IPRuleFormCancel)
			guiAuth.GET("/ip-rules/:id/edit", guiHandler.IPRuleEditForm)
			guiAuth.PUT("/ip-rules/:id", guiHandler.IPRuleUpdate)
			guiAuth.GET("/ip-rules/:id/delete", guiHandler.IPRuleDeleteConfirm)
			guiAuth.DELETE("/ip-rules/:id", guiHandler.IPRuleDelete)
			guiAuth.POST("/ip-rules/check", guiHandler.IPRuleCheckAccess)

			// My Account & 2FA management
			guiAuth.GET("/my-account", guiHandler.MyAccountPage)
			guiAuth.POST("/my-account/email", guiHandler.MyAccountUpdateEmail)
			guiAuth.POST("/my-account/password", guiHandler.MyAccountChangePassword)
			guiAuth.POST("/my-account/2fa/generate", guiHandler.MyAccount2FAGenerateTOTP)
			guiAuth.POST("/my-account/2fa/verify-totp", guiHandler.MyAccount2FAVerifyTOTP)
			guiAuth.POST("/my-account/2fa/enable-email", guiHandler.MyAccount2FAEnableEmail)
			guiAuth.POST("/my-account/2fa/disable", guiHandler.MyAccount2FADisable)
			guiAuth.GET("/my-account/2fa/status", guiHandler.MyAccount2FAStatus)
			guiAuth.POST("/my-account/2fa/regenerate-codes", guiHandler.MyAccount2FARegenerateCodes)

			// Passkey management (admin self-service)
			guiAuth.GET("/my-account/passkeys/status", guiHandler.MyAccountPasskeyStatus)
			guiAuth.POST("/my-account/passkeys/register/begin", guiHandler.MyAccountPasskeyBeginRegister)
			guiAuth.POST("/my-account/passkeys/register/finish", guiHandler.MyAccountPasskeyFinishRegister)
			guiAuth.DELETE("/my-account/passkeys/:id", guiHandler.MyAccountPasskeyDelete)
			guiAuth.POST("/my-account/passkeys/:id/rename", guiHandler.MyAccountPasskeyRename)

			// Magic link management (admin self-service)
			guiAuth.GET("/my-account/magic-link/status", guiHandler.MyAccountMagicLinkStatus)
			guiAuth.POST("/my-account/magic-link/toggle", guiHandler.MyAccountMagicLinkToggle)

			// Backup email management (admin self-service)
			guiAuth.GET("/my-account/backup-email/status", guiHandler.MyAccountBackupEmailStatus)
			guiAuth.POST("/my-account/backup-email", guiHandler.MyAccountSetBackupEmail)
			guiAuth.DELETE("/my-account/backup-email", guiHandler.MyAccountRemoveBackupEmail)

			// Trusted device management (admin self-service)
			guiAuth.GET("/my-account/trusted-devices", guiHandler.MyAccountTrustedDevices)
			guiAuth.DELETE("/my-account/trusted-devices/:device_id", guiHandler.MyAccountRevokeTrustedDevice)

			// Webhook management
			guiAuth.GET("/webhooks", guiHandler.WebhookPage)
			guiAuth.GET("/webhooks/list", guiHandler.WebhookList)
			guiAuth.GET("/webhooks/new", guiHandler.WebhookCreateForm)
			guiAuth.POST("/webhooks", guiHandler.WebhookCreate)
			guiAuth.GET("/webhooks/form-cancel", guiHandler.WebhookFormCancel)
			guiAuth.GET("/webhooks/:id/delete", guiHandler.WebhookDeleteConfirm)
			guiAuth.DELETE("/webhooks/:id", guiHandler.WebhookDelete)
			guiAuth.PUT("/webhooks/:id/toggle", guiHandler.WebhookToggle)
			guiAuth.GET("/webhooks/:id/deliveries", guiHandler.WebhookDeliveries)

			// OIDC client management (GUI)
			guiAuth.GET("/oidc-clients", guiHandler.OIDCClientsPage)
			guiAuth.GET("/oidc-clients/list", guiHandler.OIDCClientList)
			guiAuth.GET("/oidc-clients/new", guiHandler.OIDCClientCreateForm)
			guiAuth.POST("/oidc-clients", guiHandler.OIDCClientCreate)
			guiAuth.GET("/oidc-clients/form-cancel", guiHandler.OIDCClientFormCancel)
			guiAuth.GET("/oidc-clients/:id/edit", guiHandler.OIDCClientEditForm)
			guiAuth.PUT("/oidc-clients/:id", guiHandler.OIDCClientUpdate)
			guiAuth.GET("/oidc-clients/:id/delete", guiHandler.OIDCClientDeleteConfirm)
			guiAuth.DELETE("/oidc-clients/:id", guiHandler.OIDCClientDelete)
			guiAuth.POST("/oidc-clients/:id/rotate-secret", guiHandler.OIDCClientRotateSecret)

			// Session Group management
			guiAuth.GET("/session-groups", guiHandler.SessionGroupPage)
			guiAuth.GET("/session-groups/list", guiHandler.SessionGroupList)
			guiAuth.GET("/session-groups/new", guiHandler.SessionGroupCreateForm)
			guiAuth.POST("/session-groups", guiHandler.SessionGroupCreate)
			guiAuth.GET("/session-groups/form-cancel", guiHandler.SessionGroupFormCancel)
			guiAuth.GET("/session-groups/:id/edit", guiHandler.SessionGroupEditForm)
			guiAuth.PUT("/session-groups/:id", guiHandler.SessionGroupUpdate)
			guiAuth.GET("/session-groups/:id/delete", guiHandler.SessionGroupDeleteConfirm)
			guiAuth.DELETE("/session-groups/:id", guiHandler.SessionGroupDelete)
			guiAuth.GET("/session-groups/:id/apps", guiHandler.SessionGroupApps)
			guiAuth.POST("/session-groups/:id/apps", guiHandler.SessionGroupAddApp)
			guiAuth.DELETE("/session-groups/:id/apps/:app_id", guiHandler.SessionGroupRemoveApp)
		}
	}

	// OIDC Provider routes (enabled only when OIDC_ENABLED=true)
	if oidcHandler != nil {
		// Global OIDC discovery redirect to default app
		r.GET("/.well-known/openid-configuration", func(c *gin.Context) {
			defaultAppID := viper.GetString("OIDC_DEFAULT_APP_ID")
			c.Redirect(302, "/oidc/"+defaultAppID+"/.well-known/openid-configuration")
		})

		// Per-app OIDC endpoints
		oidcGroup := r.Group("/oidc/:app_id")
		{
			oidcGroup.GET("/.well-known/openid-configuration", oidcHandler.WellKnownConfiguration)
			oidcGroup.GET("/.well-known/jwks.json", oidcHandler.JWKS)
			oidcGroup.GET("/authorize", middleware.OIDCAuthorizeRateLimit(), oidcHandler.Authorize)
			oidcGroup.POST("/authorize", middleware.OIDCAuthorizeRateLimit(), oidcHandler.AuthorizeSubmit)
			oidcGroup.POST("/token", middleware.OIDCTokenRateLimit(), oidcHandler.Token)
			oidcGroup.GET("/userinfo", middleware.OIDCUserInfoRateLimit(), oidcHandler.UserInfo)
			oidcGroup.POST("/userinfo", middleware.OIDCUserInfoRateLimit(), oidcHandler.UserInfo)
			oidcGroup.POST("/introspect", middleware.OIDCIntrospectRateLimit(), oidcHandler.Introspect)
			oidcGroup.POST("/revoke", middleware.OIDCRevokeRateLimit(), oidcHandler.Revoke)
			oidcGroup.GET("/end_session", oidcHandler.EndSession)
			oidcGroup.POST("/end_session", oidcHandler.EndSession)
		}

		// Admin OIDC client management (JSON API, protected by Admin API key)
		adminOIDC := r.Group("/admin/oidc/apps/:id/clients")
		adminOIDC.Use(middleware.AdminAuthMiddleware(adminRepo))
		{
			adminOIDC.POST("", oidcHandler.AdminCreateClient)
			adminOIDC.GET("", oidcHandler.AdminListClients)
			adminOIDC.GET("/:cid", oidcHandler.AdminGetClient)
			adminOIDC.PUT("/:cid", oidcHandler.AdminUpdateClient)
			adminOIDC.DELETE("/:cid", oidcHandler.AdminDeleteClient)
			adminOIDC.POST("/:cid/rotate-secret", oidcHandler.AdminRotateClientSecret)
		}
	}

	// Add Swagger UI endpoint
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Start the server
	port := viper.GetString("PORT")
	log.Printf("Server starting on port %s", port)
	if err := r.Run(fmt.Sprintf(":%s", port)); err != nil {
		log.Fatalf("Server failed to start: %v", err)
	}
}
